### ISSUE TITLE
[image-upload] Frontend build failed - 9 test failed

### ISSUE THREAD

**Issue by samarth-p** [TejasPrabhu/Donatify#10]
Failure details - https://github.com/TejasPrabhu/Donatify/actions/runs/3566078083/jobs/5992059866

![image](https://user-images.githubusercontent.com/42717178/204314177-ef38d8f2-d3b6-4bc7-a93d-3b0ae0a93bfb.png)

**Comment by Naveen-Jayanna** [comment]
Need an update on this. Are you facing the same issue after updating the code?

**Comment by Naveen-Jayanna** [comment]
Works fine after the final merge. Closing the issue.
